version: '3.3'

services:

  db:
    image: mariadb
    command: --init-file /init/user-init.sql
    ports:
      - 3309:3306
    environment:
      MYSQL_USER: q
      MYSQL_PASSWORD: q
      MYSQL_ROOT_PASSWORD: test
    volumes:
      - ./db/user-init.sql:/init/user-init.sql
      - ./db/etc:/etc/mysql/conf.d
      - ./db/logs:/var/lib/mysql/logs

  front:
    build:
      context: ./front
      dockerfile: ./Dockerfile

  nginx:
    depends_on:
      - front
    build:
      context: ./nginx
    volumes:
    - ./nginx/logs:/var/log/nginx